const SETTINGS_CSS = `
.dsh-bg-preview-image,.dsh-bg-preview-mask{position:absolute;inset:0;background-position:center;pointer-events:none}
.dsh-bg-mini{position:relative;width:100%;height:100%;display:grid;grid-template-columns:28% 1fr;font-size:11px;pointer-events:none}
.dsh-bg-mini aside{display:flex;flex-direction:column;gap:18px;padding:16px 10px;border-right:1px solid var(--dsw-alias-border-l1)}
.dsh-bg-mini main{display:flex;flex-direction:column;gap:12px;padding:22px 12px}.dsh-bg-mini main>div{margin-top:auto;border-radius:10px;padding:10px;border:1px solid var(--dsw-alias-border-l1)}
.dsh-bg-settings{color:var(--dsw-alias-label-primary);padding:8px 0 24px;max-width:640px;--bg-accent:var(--dsw-alias-brand-primary)}
.dsh-bg-settings *{box-sizing:border-box}.dsh-bg-settings h2{font-size:22px;letter-spacing:-.4px;margin:0 0 8px;font-weight:650}.dsh-bg-settings p{margin:0}
.dsh-bg-muted{font-size:12px;line-height:1.7;color:var(--dsw-alias-label-secondary)}
.dsh-bg-card{background:var(--dsw-alias-bg-layer-1);border:1px solid var(--dsw-alias-border-l1);border-radius:16px;padding:18px;margin-top:18px;overflow:hidden}
.dsh-bg-top{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:14px}.dsh-bg-title{font-size:14px;font-weight:600}.dsh-bg-tag{font-size:11px;color:var(--bg-accent);background:color-mix(in srgb,var(--bg-accent) 9%,transparent);padding:4px 8px;border-radius:6px;white-space:nowrap}
.dsh-bg-preview{height:190px;position:relative;border-radius:12px;overflow:hidden;background:var(--dsw-alias-bg-layer-2);border:1px solid var(--dsw-alias-border-l1);display:grid;place-items:center}
.dsh-bg-preview img{width:100%;height:100%;object-fit:cover}.dsh-bg-empty{text-align:center;padding:18px}.dsh-bg-empty svg{color:var(--bg-accent);margin-bottom:8px}.dsh-bg-empty strong{display:block;font-size:13px;margin-bottom:4px}
.dsh-bg-upload{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-top:14px}.dsh-bg-filename{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px;color:var(--dsw-alias-label-secondary)}
.dsh-bg-button{font:inherit;font-size:12px;font-weight:500;padding:8px 12px;border-radius:8px;border:1px solid var(--dsw-alias-border-l2);color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-1);cursor:pointer;white-space:nowrap}.dsh-bg-button:hover{background:var(--dsw-alias-bg-layer-2)}.dsh-bg-button:disabled{opacity:.45;cursor:default}.dsh-bg-primary{color:white;background:var(--bg-accent);border-color:transparent}.dsh-bg-primary:hover{background:color-mix(in srgb,var(--bg-accent) 88%,black)}
.dsh-bg-switch{width:38px;height:22px;border:0;border-radius:99px;padding:3px;background:var(--dsw-alias-border-l2);cursor:pointer;transition:background .15s}.dsh-bg-switch[aria-checked=true]{background:var(--bg-accent)}.dsh-bg-switch span{display:block;width:16px;height:16px;background:white;border-radius:50%;transition:transform .15s;box-shadow:0 1px 3px #0002}.dsh-bg-switch[aria-checked=true] span{transform:translateX(16px)}
.dsh-bg-control{padding:14px 0;border-top:1px solid var(--dsw-alias-border-l1)}.dsh-bg-control-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:5px;font-size:13px}.dsh-bg-value{font-variant-numeric:tabular-nums;color:var(--bg-accent);font-size:12px;background:color-mix(in srgb,var(--bg-accent) 8%,transparent);padding:3px 7px;border-radius:6px;min-width:42px;text-align:center}
.dsh-bg-control input[type=range]{width:100%;margin:12px 0 0;accent-color:var(--bg-accent);cursor:pointer;height:18px}.dsh-bg-control input:disabled{cursor:default}
.dsh-bg-segments{display:flex;gap:4px;padding:4px;background:var(--dsw-alias-bg-layer-2);border-radius:10px;margin-top:12px}.dsh-bg-segments button{flex:1;border:0;background:transparent;color:var(--dsw-alias-label-secondary);padding:8px 4px;font:inherit;font-size:12px;border-radius:7px;cursor:pointer}.dsh-bg-segments button[aria-pressed=true]{background:var(--dsw-alias-bg-layer-1);color:var(--bg-accent);box-shadow:0 1px 4px #0001;font-weight:600}
.dsh-bg-footer{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-top:18px}.dsh-bg-status{font-size:12px;color:var(--dsw-alias-label-secondary)}.dsh-bg-status[role=alert]{color:var(--dsw-alias-state-error-primary)}
.dsh-bg-settings button:focus-visible,.dsh-bg-settings input:focus-visible{outline:2px solid var(--bg-accent);outline-offset:3px}.dsh-bg-settings fieldset{border:0;padding:0;margin:0;min-width:0}.dsh-bg-settings fieldset:disabled .dsh-bg-switch{opacity:.5}
@media(max-width:520px){.dsh-bg-card{padding:14px}.dsh-bg-preview{height:150px}.dsh-bg-footer{align-items:flex-start;flex-direction:column}}
`;
